create table food
(
    accessibilityOptionsHasWheelchairAccessibleEntrance tinyint(1)    not null,
    accessibilityOptionsHasWheelchairAccessibleRestroom tinyint(1)    not null,
    accessibilityOptionsHasWheelchairAccessibleSeating  tinyint(1)    not null,
    accessibilityOptionsHasWheelchairAccessibleParking  tinyint(1)    not null,
    businessStatus                                      varchar(1024) not null,
    id                                                  varchar(64)   not null
        primary key,
    hasDelivery                                         tinyint(1)    not null,
    hasDineIn                                           tinyint(1)    null,
    servesVegetarianFood                                varchar(1024) null,
    displayName                                         varchar(1024) not null,
    formattedAddress                                    varchar(1024) not null,
    locationLat                                         double        not null,
    locationLng                                         double        not null,
    nationalPhoneNumber                                 varchar(1024) not null,
    regularOpeningHoursPeriods                          json          null,
    regularOpeningHoursWeekdayDescriptions              json          null,
    paymentOptionsAcceptsCreditCards                    tinyint(1)    not null,
    paymentOptionsAcceptsDebitCards                     tinyint(1)    not null,
    paymentOptionsAcceptsCashOnly                       tinyint(1)    not null,
    paymentOptionsAcceptsNfc                            tinyint(1)    not null,
    photoLink                                           varchar(1024) not null,
    priceLevel                                          varchar(1024) null,
    rating                                              double        not null,
    hasTakeout                                          tinyint(1)    not null,
    types                                               json          not null,
    userRatingCount                                     bigint        not null,
    websiteURI                                          varchar(1024) null,
    editorialSummary                                    varchar(1024) null,
    parkingOptionsHasFreeParkingLot                     tinyint(1)    not null,
    parkingOptionsHasPaidParkingLot                     tinyint(1)    not null,
    parkingOptionsHasFreeStreetParking                  tinyint(1)    not null,
    parkingOptionsHasPaidStreetParking                  tinyint(1)    not null,
    parkingOptionsHasValetParking                       tinyint(1)    not null,
    parkingOptionsHasFreeGarageParking                  tinyint(1)    not null,
    parkingOptionsHasPaidGarageParking                  tinyint(1)    not null,
    regularOpeningHours                                 varchar(1024) null
);

